### ISSUE TITLE
Docker image mantalab/manta-node:w3f-milestone-1 dies after a few seconds

### ISSUE THREAD

**Issue by Garandor** [Manta-Network/manta-node#19]
**Description**

as it says on the tin. I'm running this on a super low-spec device (see below, not sure if it's due to resource overrun)
~Interestingly, i cannot see the image at https://hub.docker.com/search?q=mantalabs&type=image~
Just found out it there is another one called mantalab - without the s - as it says in the title and it shows ther

**Steps to Reproduce**
```bash
su
docker pull mantalab/manta-node:w3f-milestone-1
docker container run -p 9944:9944 mantalab/manta-node:w3f-milestone-1
```
=> Succeeds, container runs for a few seconds, then exits
```bash
$ docker ps -a
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS          PORTS                    NAMES
d96110418241   mantalab/manta-node:w3f-milestone-1                  "./target/release/ma…"   2 minutes ago   Up 4 seconds    0.0.0.0:9944->9944/tcp   manta
$ docker ps -a
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS          PORTS                    NAMES
d96110418241   mantalab/manta-node:w3f-milestone-1                  "./target/release/ma…"   2 minutes ago   Up 5 seconds    0.0.0.0:9944->9944/tcp   manta
$ docker ps -a
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS          PORTS                    NAMES
d96110418241   mantalab/manta-node:w3f-milestone-1                  "./target/release/ma…"   2 minutes ago   Up 6 seconds    0.0.0.0:9944->9944/tcp   manta
$ docker ps -a
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS          PORTS                    NAMES
d96110418241   mantalab/manta-node:w3f-milestone-1                  "./target/release/ma…"   2 minutes ago   Up 6 seconds    0.0.0.0:9944->9944/tcp   manta
$ docker ps -a
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS                       PORTS       NAMES
d96110418241   mantalab/manta-node:w3f-milestone-1                  "./target/release/ma…"   2 minutes ago   Exited (132) 6 seconds ago               manta
```
** Environment **
OS: Archlinux amd64
CPU: AMD A6 APU 4x1.4GHz
RAM: 4 GB + 4 GB swap
Docker 20.10.3

**Expected vs. Actual Behavior**

Naively - I would expect the node to run in the background and expose an RPC endpoint for the frontend to attach to.
I just started playing around with the manta repos though - could be I'm missing something.
`docker logs` comes up empty, if I can provide logs some other way please let me know

**Comment by zhenfeizhang** [comment]
hmmm.. I am not sure what is the issue. It would be great if you can provide more details.

were you able to build from the source file in this repo?

**Comment by Garandor** [comment]
My ancient laptop I tried running it on definitely doesn't support avx2.
I re-ran it on a beefier one and can confirm that the node starts up normally.

Now I'm wondering, if AVX2 is strictly necessary, i think the node should check for its existence by grepping /proc/cpuinfo before executing any extended logic - that way it can print a clear error message and exit normally.
This is probably an UX improvement that would be better fixed upstream by substrate-node repo's devs. If you agree @zhenfeizhang  just close the issue here and I will open one in the substrate-node repo

**Comment by zhenfeizhang** [comment]
right. Manta did not use any AVX2 feature. But some of the dependencies may.
The node is not meant to run over an ancient laptop anyway...

Closed for now.
